name: Deploy Extension

on:
  push:
    branches:
      - master # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install
      - run: npm install -g vsce
      - run: vsce package
      - run: vsce publish -p ${{ secrets.VS_MARKETPLACE_PAT }}
